/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.anderson.frame;

import br.com.anderson.objeto.Aluno;
import javax.swing.JOptionPane;

/**
 *
 * @author SATC
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPAluno = new javax.swing.JPanel();
        jLAluno = new javax.swing.JLabel();
        jLMatricula = new javax.swing.JLabel();
        jTFMatricula = new javax.swing.JTextField();
        jLNome = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jBCadastrar = new javax.swing.JButton();
        jPNotas = new javax.swing.JPanel();
        jPSeparador = new javax.swing.JPanel();
        jLDisciplina = new javax.swing.JLabel();
        jTFDisciplina = new javax.swing.JTextField();
        jLNotas = new javax.swing.JLabel();
        jLN1 = new javax.swing.JLabel();
        jLN2 = new javax.swing.JLabel();
        jLN3 = new javax.swing.JLabel();
        jLN4 = new javax.swing.JLabel();
        jTFN1 = new javax.swing.JTextField();
        jTFN2 = new javax.swing.JTextField();
        jTFN3 = new javax.swing.JTextField();
        jTFN4 = new javax.swing.JTextField();
        jBCalcular = new javax.swing.JButton();
        jCBDisciplina = new javax.swing.JComboBox<>();
        jBSair = new javax.swing.JButton();
        jLTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPAluno.setBackground(new java.awt.Color(0, 153, 102));
        jPAluno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLAluno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLAluno.setText("Aluno");

        jLMatricula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLMatricula.setText("Matrícula");

        jLNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLNome.setText("Nome");

        jBCadastrar.setText("Cadastrar");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPAlunoLayout = new javax.swing.GroupLayout(jPAluno);
        jPAluno.setLayout(jPAlunoLayout);
        jPAlunoLayout.setHorizontalGroup(
            jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPAlunoLayout.createSequentialGroup()
                .addGroup(jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPAlunoLayout.createSequentialGroup()
                        .addGroup(jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPAlunoLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLAluno))
                            .addGroup(jPAlunoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLMatricula)))
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addGroup(jPAlunoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTFNome)
                            .addComponent(jTFMatricula, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPAlunoLayout.createSequentialGroup()
                                .addComponent(jLNome)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBCadastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPAlunoLayout.setVerticalGroup(
            jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLAluno)
                .addGap(48, 48, 48)
                .addComponent(jLMatricula)
                .addGap(18, 18, 18)
                .addComponent(jTFMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLNome)
                .addGap(29, 29, 29)
                .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jBCadastrar)
                .addContainerGap())
        );

        jPNotas.setBackground(new java.awt.Color(0, 153, 102));
        jPNotas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPSeparador.setBackground(new java.awt.Color(0, 0, 0));
        jPSeparador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPSeparadorLayout = new javax.swing.GroupLayout(jPSeparador);
        jPSeparador.setLayout(jPSeparadorLayout);
        jPSeparadorLayout.setHorizontalGroup(
            jPSeparadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPSeparadorLayout.setVerticalGroup(
            jPSeparadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLDisciplina.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLDisciplina.setText("Nome da Disciplina");

        jLNotas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLNotas.setText("Notas");

        jLN1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLN1.setText("N1");

        jLN2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLN2.setText("N2");

        jLN3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLN3.setText("N3");

        jLN4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLN4.setText("N4");

        jBCalcular.setText("Calcular");
        jBCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalcularActionPerformed(evt);
            }
        });

        jCBDisciplina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prova", "Seminário", "Trabalho" }));

        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPNotasLayout = new javax.swing.GroupLayout(jPNotas);
        jPNotas.setLayout(jPNotasLayout);
        jPNotasLayout.setHorizontalGroup(
            jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNotasLayout.createSequentialGroup()
                .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPNotasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTFDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPNotasLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLDisciplina))
                    .addGroup(jPNotasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCBDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPNotasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBCalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBSair))
                    .addGroup(jPNotasLayout.createSequentialGroup()
                        .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPNotasLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLNotas))
                            .addGroup(jPNotasLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLN2)
                                    .addComponent(jLN1)
                                    .addComponent(jLN3)
                                    .addComponent(jLN4))
                                .addGap(18, 18, 18)
                                .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFN4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFN2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFN1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFN3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 45, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPNotasLayout.setVerticalGroup(
            jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPSeparador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPNotasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPNotasLayout.createSequentialGroup()
                        .addComponent(jLDisciplina)
                        .addGap(50, 50, 50)
                        .addComponent(jTFDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPNotasLayout.createSequentialGroup()
                        .addComponent(jLNotas)
                        .addGap(36, 36, 36)
                        .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLN1)
                            .addComponent(jTFN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPNotasLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLN2)
                            .addComponent(jTFN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLN3)
                            .addComponent(jTFN3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLN4)
                            .addComponent(jTFN4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBCalcular)
                            .addComponent(jBSair))
                        .addContainerGap())
                    .addGroup(jPNotasLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jCBDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLTitulo.setText("Cadastro e Consulta de Notas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPNotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLTitulo)
                        .addGap(128, 128, 128))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPNotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCalcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBCalcularActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        // TODO add your handling code here:
        String nome, disciplina;
        int matricula;
        
        matricula = Integer.parseInt(jTFMatricula.getText());
        nome = jTFNome.getText();
        disciplina = jTFDisciplina.getText();
        
        Aluno a = new Aluno (nome, matricula);
        
        JOptionPane.showMessageDialog(this, a.toString());
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jBSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBCalcular;
    private javax.swing.JButton jBSair;
    private javax.swing.JComboBox<String> jCBDisciplina;
    private javax.swing.JLabel jLAluno;
    private javax.swing.JLabel jLDisciplina;
    private javax.swing.JLabel jLMatricula;
    private javax.swing.JLabel jLN1;
    private javax.swing.JLabel jLN2;
    private javax.swing.JLabel jLN3;
    private javax.swing.JLabel jLN4;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLNotas;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JPanel jPAluno;
    private javax.swing.JPanel jPNotas;
    private javax.swing.JPanel jPSeparador;
    private javax.swing.JTextField jTFDisciplina;
    private javax.swing.JTextField jTFMatricula;
    private javax.swing.JTextField jTFN1;
    private javax.swing.JTextField jTFN2;
    private javax.swing.JTextField jTFN3;
    private javax.swing.JTextField jTFN4;
    private javax.swing.JTextField jTFNome;
    // End of variables declaration//GEN-END:variables
}
